# Copyright 2020 Novo Nordisk Foundation Center for Biosustainability,
# Technical University of Denmark.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""Test the response generated by the client."""


from urllib.error import HTTPError
from urllib.request import build_opener

import pytest

from tag_spy.http_client import Client


@pytest.fixture()
def client() -> Client:
    """Return a client instance."""
    return Client(opener=build_opener(), base_url="https://httpbin.org/status/")


@pytest.mark.parametrize(
    "status",
    [
        200,
        pytest.param(
            400, marks=pytest.mark.raises(exception=HTTPError, message="BAD REQUEST")
        ),
        pytest.param(
            500,
            marks=pytest.mark.raises(exception=HTTPError, message="INTERNAL SERVER"),
        ),
    ],
)
def test_from_tag(client, status: int) -> None:
    """Test that the response has the expected status code."""
    assert client.get(path=str(status)).status == status
