name: CD

on:
  push:
    tags:
      - '[0-9].[0-9].[0-9]'
      - '[0-9]+.[0-9]+.[0-9]+a[0-9]+'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install tox tox-gh-actions
      - name: Test with tox
        run: tox
      - name: Build package
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.7' }}
        run: python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.7' }}
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m pip install twine
          twine check dist/*
          twine upload --skip-existing --non-interactive dist/*
      - name: Create GitHub release
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.7' }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Please see
            https://github.com/${{ github.repository }}/blob/${{ github.ref }}/CHANGELOG.rst#${{ github.ref }}
            for the full release notes.
          draft: false
          prerelease: false
